version: "3"

services:
  # Postgres Configs
  db:
    container_name: db_postgres_sql
    image: postgres
    environment:
      POSTGRES_USER: ""
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: ""
    networks:
      - app_network
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # NodeJs API config
  app:
    container_name: app_node
    networks:
      - app_network
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db

networks:
  app_network:
    driver: bridge
